name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.5

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.5

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=covprofile -v ./...