name: CI

on:
  push:

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create a release
        id: release
        if: github.ref == 'refs/heads/master'
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.5

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.5

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=covprofile -v ./...